### ISSUE TITLE
Examining in darkness thing needs fixes

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1024]
#### Description of issue

If you examine something in your hand or on your person and you're in the dark, you get a failure message even though it's (say) a headset on your ears.

#### Difference between expected and actual behavior

Examining items on your person/in your hand should work even in the dark, but it doesn't.

#### Steps to reproduce

go somewhere relatively dark, examine something on your person

#### Length of time in which bug has been known to occur

Since the server went back to 24/7. I'm guessing it's when The Dark Elites did that can_see thing.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cnb-c6tV

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TheDarkElites** [comment]
working on a fix rn
