### ISSUE TITLE
ID cards aren't visible

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1025]
#### Description of issue

Used to be if you examine someone you could open up their ID, now it's not visible

#### Difference between expected and actual behavior

You should be able to read the ID

#### Steps to reproduce

Examine someone
Check for ID

#### Length of time in which bug has been known to occur

Probably related to The Dark Elites vision shit

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cnb-c6tV

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TheDarkElites** [comment]
This shouldn't be related. The examine proc was untouched aside from the initial vision check. There should be no reason for something to pop up on examine but not everything. Ill look into it anyway.

**Comment by TheDarkElites** [comment]
further investigation shows they are related, adding to my fix for seeing your own equipment.
