### ISSUE TITLE
HCZ checkpoint issue

### ISSUE THREAD

**Issue by DaHidd3nG3rman** [Foundation-19/Foundation-19#1085]
#### Description of issue

HCZ Checkpoint controls

#### Difference between expected and actual behavior

the buttons for the blast doors on the right and left of the bubble have no controls to be closed the left side can be from the outside the right one cannot?

#### Steps to reproduce

Head on over the the HCZ checkpoint and try it yourself? even checked the buttons on the side where the new laptops are

#### Specific information for locating

right and left of HCZ checkpoint the blastdoors

![Screenshot 2023-04-16 230318](https://user-images.githubusercontent.com/88110281/232333114-1e20f194-b77c-485e-b99d-531b5cd1ecf3.png)

#### Client version, Server revision & Game ID

Round ID: cnm-cOXU
BYOND Version: 514.1585
Server revision compiled on: 2023-04-16T15:28:19+00:00

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
Not sure if this has been fixed with any of the checkpoint changes but I'll take a look at it later. 

Looks like an easy enough mapping fix if not.

**Comment by TerryTehCoder** [comment]
The HCZ checkpoint has since been redesigned and this is no longer an issue.

**Comment by projectkepler-ru** [comment]
@TheDarkElites  close this

**Comment by islaughterfunny** [comment]
nuh uh
