### ISSUE TITLE
scp-2427-3 intercom no work

### ISSUE THREAD

**Issue by IDKWUTNAME** [Foundation-19/Foundation-19#1093]
#### Description of issue
SCP-2427-3's intercom prolly doesn't work. When I played as the spider, I could hear other people and see my messages transmit, but nobody actually responded. 

#### Difference between expected and actual behavior

The spider prolly shouldn't be ignored if they're gonna be in a cell all day.

#### Steps to reproduce

Be the spider and try having a conversation in your containment.

#### Specific information for locating

I dunno

#### Length of time in which bug has been known to occur

Issue been happening since today atleast

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by checkraisefold** [comment]
probably related to #1011

**Comment by TheDarkElites** [comment]
Intercom is considered radio transmission, which has slightly different checks with the audio_memetics system in can_hear to account for radio users usually not seeing each other. So no, this is not related to #1011.

**Comment by checkraisefold** [comment]
set your default language to english in IC > check known languages, works fine
free to close
