### ISSUE TITLE
Humanoid containment area has impossible to get to beaker box

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#1121]
#### Description of issue

tin
#1097 @GGarciaECE 

#### Difference between expected and actual behavior

i want to be able to get the beakers

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/19525688/233760308-fc599d51-39c1-4455-9eb2-9da29e5f62e9.png)

**Comment by GGarciaECE** [comment]
Fixin
