### ISSUE TITLE
LCZ Sec door has incorrect access

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#1122]
#### Description of issue

tin

#### Difference between expected and actual behavior

the poor lcz guards spawn in there and then are trapped until god intervenes and edits the door access live

#### Steps to reproduce

lcz guards have level 2 security access. the door is level 3 required
![image](https://user-images.githubusercontent.com/19525688/233760412-16e21172-b9c0-46da-9cc4-20165cad031b.png)

**Comment by GGarciaECE** [comment]
Fixed in latest commit
