### ISSUE TITLE
SCP-2427-3 and SCP-049 cannot pry open doors

### ISSUE THREAD

**Issue by PzkpfwVIAusfH** [Foundation-19/Foundation-19#1141]
#### Description of issue
SCP-049 and SCP-2427-3 cannot pry open doors

(Note: I have not had the chance to test it as SCP-049. I was told by others).

#### Difference between expected and actual behavior
It is expected that these SCPs should be able to open the doors, except their containments (Except 2427-3 who is supposed to when enraged)

#### Steps to reproduce
As SCP-2427-3: Wait to be enraged ->try to open containment door -> Fail.

If let out: Try to pry open any door ->fail

SCP-049: Refer to the "If let out" tab 

#### Specific information for locating

![Screenshot 2023-05-01 000348](https://user-images.githubusercontent.com/110554289/235378798-0c22aa0f-3d05-42e2-b6b3-12d52ec76732.png)

#### Length of time in which bug has been known to occur

Quite recent. As far as I know since 17/04/2023

#### Client version, Server revision & Game ID

![image](https://user-images.githubusercontent.com/110554289/235378919-fc4badac-c94d-4a3d-8a13-1b5158c81f0c.png)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by EgorDinamit** [comment]
Chances are, for 2427-3, you accidentally pressed rest or otherwise entered that state, which prevents you from finishing do_afters.

**Comment by Tuulipommi** [comment]
SCP-049 is not supposed to pry doors open, at least not in my opinion...
