### ISSUE TITLE
Archive fax machine not properly logging in

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1156]
#### Description of issue

The fax machine in the Archive area won't let you log in

#### Difference between expected and actual behavior

It should let you log in

#### Steps to reproduce

Try to use the Archive fax machine

#### Specific information for locating

Other fax machines might be broken as well

#### Length of time in which bug has been known to occur

no clue

#### Issue bingo

- [x] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by 77seven77seven** [comment]
This might be a mapping issue where fax machines aren't properly set up.

**Comment by aidan-bowman** [comment]
Archive got replaced + the description isn't... descriptive.
