### ISSUE TITLE
Mentors able to skip/cancel votes.

### ISSUE THREAD

**Issue by Tuulipommi** [Foundation-19/Foundation-19#1157]
#### Description of issue

Mentors can veto/skip votes, even though they are not supposed to be able to.

#### Difference between expected and actual behavior

N/A

#### Steps to reproduce

Have the +Mentor and skip a active vote.

#### Specific information for locating

Start a vote, then have someone with +Mentor cancel the vote.

#### Length of time in which bug has been known to occur

Since the beginning.

#### Client version, Server revision & Game ID

N/A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TheDarkElites** [comment]
Checked and this seems to no longer be occurring as a bug.
