### ISSUE TITLE
Cleaner is called Space Cleaner

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1210]
Muh immershun

**Comment by TheDarkElites** [comment]
did not follow bug template, -1000 social credit score.

**Comment by aidan-bowman** [comment]
> did not follow bug template, -1000 social credit score.

that's cause our template is SHIT

**Comment by HaultyAnonie** [comment]
Resolved in https://github.com/Foundation-19/Foundation-19/pull/1213

**Comment by TheDarkElites** [comment]
> Resolved in #1213

If you put fix: fixed #1210 into your pr's changelog it will automatically assign that pr as a fix for this issue.
