### ISSUE TITLE
DCZ chem machine needs a chem cartridge

### ISSUE THREAD

**Issue by bobjension** [Foundation-19/Foundation-19#1240]
#### Description of issue

all the different escape routes aside from the checkpoint are not accessible, all of them require thermite which can only be acquired by a chem machine, now the major issue about the chem machine is the ability to make acid, but that requires prep and planning to even access the chem machine.

#### Difference between expected and actual behavior

it should have a chem cartridge instead of being empty, and I don't think you can get it in CDZ by mining or any other hidden mechanic.
 
 
 
#### Length of time in which bug has been known to occur
	The last time DCZ got remapped

![chem machine 2](https://github.com/Foundation-19/Foundation-19/assets/76455911/7e3f08af-e569-4309-9889-c706cbf8c080)
![chem machine 3](https://github.com/Foundation-19/Foundation-19/assets/76455911/58192de4-b0ad-4370-8c2f-f3450d281e95)
![chem machine](https://github.com/Foundation-19/Foundation-19/assets/76455911/ff989e2b-e0b3-488b-902b-f4631a594005)
![chemmachine4](https://github.com/Foundation-19/Foundation-19/assets/76455911/ace98680-b1b9-44a8-b7b2-22d472b818bb)

**Comment by HaultyAnonie** [comment]
The description is dumb; you just contradicted your point about thermite, by having to require prep.
You can also just... use a toolbox on the wall to deconstruct it.. or use a gun....

I disagree.

**Comment by aidan-bowman** [comment]
> The description is dumb; you just contradicted your point about thermite, by having to require prep. You can also just... use a toolbox on the wall to deconstruct it.. or use a gun....
> 
> I disagree.

shut up

**Comment by HaultyAnonie** [comment]
> > The description is dumb; you just contradicted your point about thermite, by having to require prep. You can also just... use a toolbox on the wall to deconstruct it.. or use a gun....
> > I disagree.
> 
> shut up

You're not a medical main.

**Comment by HaultyAnonie** [comment]
We have it hard enough as is.

**Comment by bobjension** [comment]
> The description is dumb; you just contradicted your point about thermite, by having to require prep. You can also just... use a toolbox on the wall to deconstruct it.. or use a gun....
> 
> I disagree.

we don't get a toolbox??, and 9mm doesn't destroy walls anymore

**Comment by HaultyAnonie** [comment]
The real issue should be that even one unit of thermite can burn down a whole wall, the quantity of thermite splashed should be taken in consideration in the code.

Acid is already taken into consideration.

Additionally, I don't see how adding a chemistry cartridge to chemical dispensers makes it easier to make acid/thermite, you can still make it without the chemistry cartridge.

I believe there was a PR stopping D-Class from using chemistry dispensers or something along those lines, however.

**Comment by bobjension** [comment]
you can't really make thermite with ghetto chem or at least we don't have the liquids required to make them, and that PR just made it so you have to be trained in chem to use it 100% of the time, and d class can take trained in chem, and once again, literally all of the escape routes require thermite or at least something that can break the walls, they also nerfed acid I'm pretty sure.

> The real issue should be that even one unit of thermite can burn down a whole wall, the quantity of thermite splashed should be taken in consideration in the code.
> 
> Acid is already taken into consideration.
> 
> Additionally, I don't see how adding a chemistry cartridge to chemical dispensers makes it easier to make acid/thermite, you can still make it without the chemistry cartridge.
> 
> I believe there was a PR stopping D-Class from using chemistry dispensers or something along those lines, however.

**Comment by HaultyAnonie** [comment]
> you can't really make thermite with ghetto chem or at least we don't have the liquids required to make them, and that PR just made it so you have to be trained in chem to use it 100% of the time, and d class can take trained in chem, and once again, literally all of the escape routes require thermite or at least something that can break the walls, they also nerfed acid I'm pretty sure.
> 
> > The real issue should be that even one unit of thermite can burn down a whole wall, the quantity of thermite splashed should be taken in consideration in the code.
> > Acid is already taken into consideration.
> > Additionally, I don't see how adding a chemistry cartridge to chemical dispensers makes it easier to make acid/thermite, you can still make it without the chemistry cartridge.
> > I believe there was a PR stopping D-Class from using chemistry dispensers or something along those lines, however.

What's any of that have to do with your reason to add chem cartridges?
Also this was more of a suggestion not an issue.

**Comment by aidan-bowman** [comment]
> > you can't really make thermite with ghetto chem or at least we don't have the liquids required to make them, and that PR just made it so you have to be trained in chem to use it 100% of the time, and d class can take trained in chem, and once again, literally all of the escape routes require thermite or at least something that can break the walls, they also nerfed acid I'm pretty sure.
> > > The real issue should be that even one unit of thermite can burn down a whole wall, the quantity of thermite splashed should be taken in consideration in the code.
> > > Acid is already taken into consideration.
> > > Additionally, I don't see how adding a chemistry cartridge to chemical dispensers makes it easier to make acid/thermite, you can still make it without the chemistry cartridge.
> > > I believe there was a PR stopping D-Class from using chemistry dispensers or something along those lines, however.
> 
> What's any of that have to do with your reason to add chem cartridges? Also this was more of a suggestion not an issue.

yes it IS an issue, the chem dispensers are supposed to WORK

**Comment by HaultyAnonie** [comment]
> yes it IS an issue, the chem dispensers are supposed to WORK

they do?
