### ISSUE TITLE
SCP TAG on PCarriers

### ISSUE THREAD

**Issue by HaultyAnonie** [Foundation-19/Foundation-19#1241]
#### Description of issue

When you remove the accessory blue SCP Tags on plate carriers- they don't have a sprite so it's basically an invisible object in your hand.

#### Difference between expected and actual behaviour

Add a blue sprite to indicate it's there. It's weird behaviour, ruins realism.

#### Steps to reproduce

Remove accessory on guard plate carrier.

#### Specific information for locating

There's not even any span_notices to say you removed it off your armor.

#### Length of time in which bug has been known to occur

Anytime.

#### Client version, Server revision & Game ID

Anytime.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by aidan-bowman** [comment]
> #### Issue bingo
> * [ x] Issue could be reproduced at least once
> * [x ] Issue could be reproduced by different players
> * [ x] Issue could be reproduced in multiple rounds
> * [ x] Issue happened in a recent (less than 7 days ago) round
> * [x ] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

BWAHAHAHAHAHAHAA

**Comment by TheDarkElites** [comment]
[x ] -> [x]
