### ISSUE TITLE
The nanomed in 049 medical storage has an access requirement on it

### ISSUE THREAD

**Issue by ChuChu42** [Foundation-19/Foundation-19#1256]
#### Description of issue
the nanomed in 049's medical storage has an access requirement on it, due to this, 049 is unable to dispense medicine from it, as for they dont have the ID of an medical doctor

#### Difference between expected and actual behavior

Not having a access requirement on the vendor is whats expected
it having a requirement is not

#### Steps to reproduce
1. be 049
2. go to medical storage
3. click on nanomed
4. unable to use it

#### Specific information for locating

NanoMed Plus in 049 Medical Storage

#### Length of time in which bug has been known to occur

since nanomed was added

#### Client version, Server revision & Game ID

TGS version: 5.13.4
Round ID: cpa-b0XL
BYOND Version: 514.1585
Server revision compiled on: 2023-08-06T13:11:44+00:00
Master commit: [b8718898d8acd8f835a5f4e1412c750a4f449454](https://github.com/Foundation-19/Foundation-19/commit/b8718898d8acd8f835a5f4e1412c750a4f449454)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
Unable to reproduce in revision compiled on 24-03-10. No access requirement in StrongDmm nor in-game. Likely fixed sometime in the past. 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/8f509a2e-08cb-4efd-af73-a2d377434cc3)
