### ISSUE TITLE
Taking 0.5 out of a bandage of any type resets it to it's original world-value. (DUPLICATION!!!)

### ISSUE THREAD

**Issue by HaultyAnonie** [Foundation-19/Foundation-19#1267]
#### Description of issue

If you split some bandage in your hand to 0.1 or any float for that matter- it will duplicate in your new hand **completely usable** and the original stack just loses 0.**?** of what you removed.

#### Difference between expected and actual behavior

You should of gotten your float number split and not have it duped.

E.G:
**Split Stacks** 5 original.
**_How many stacks of the resin patches would you like to split off_**

_Chooses 0.1_

Outcome:
**Gets a brand new stack of 5 and 4.9 in the original stack.**

#### Specific information for locating

**medical.dm** is all the code relating to bandages and splints.

#### Length of time in which bug has been known to occur

During the round.

#### Client version, Server revision & Game ID

Localhost.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by HaultyAnonie** [comment]
Or you can just take out 100 and just duplicate it lol.

**Comment by aidan-bowman** [comment]
Testing reveals this happens with every obj/item/stack

**Comment by aidan-bowman** [comment]
> Or you can just take out 100 and just duplicate it lol.

Couldn't replicate
