### ISSUE TITLE
Port Ratvar from TG and Change NarSie and Ratvar to fit SCP Universe

### ISSUE THREAD

**Issue by Tuulipommi** [Foundation-19/Foundation-19#1305]
#### Description of enhancement

Basically, importing Ratvar from TG to F19, and then editing it, turning it into the Clockwork God, and then also editing NarSie, turning it into the Scarlet King.

**Comment by Tsurupeta** [comment]
didn't /tg/ remove ratvar?

**Comment by aidan-bowman** [comment]
> didn't /tg/ remove ratvar?

i believe bee has it

**Comment by aidan-bowman** [comment]
Personally i think it would be better to code our own cults from scratch than to just copy and paste other server's cults.

**Comment by Tuulipommi** [comment]
> Personally i think it would be better to code our own cults from scratch than to just copy and paste other server's cults.

If you all wanna do it, sure.

**Comment by 77seven77seven** [comment]
merged cult PR fixes this

**Comment by 77seven77seven** [comment]
pls close this is already fixed!!!! 11!1!

**Comment by aidan-bowman** [comment]
huh i can close issues
