### ISSUE TITLE
The operating computer and PDA medical scanner do not work.

### ISSUE THREAD

**Issue by quadbium** [Foundation-19/Foundation-19#1312]
#### Description of issue
The operating computer and PDA medical scanner do not display a medical scan
![computer broke](https://github.com/Foundation-19/Foundation-19/assets/138327811/ae5009a6-eb2a-4f28-a202-3e2bf35b695f)
![PDA](https://github.com/Foundation-19/Foundation-19/assets/138327811/d7ea791e-db6c-4eec-bf3c-ee14b1a91e2f)

#### Difference between expected and actual behavior
A medical scan and patent information should show up, instead of "list"

#### Specific information for locating

A  buckle a human or monkey onto an operating table next to an Operating computer
B  1 Install a "Computer accessory (medical scanner module)" into a PDA
    2 scan yourself with the PDA

#### Length of time in which bug has been known to occur

seems to have started on  September 16, after the "SCP refactor" PR began testing.

#### Client version, Server revision & Game ID

Round ID: cpQ-afMq
BYOND Version: 514.1585
Server revision compiled on: 2023-09-17T00:26:49+00:00
Master commit: [84abb9f709ba1f6cef180f236a46eb046a64239d](https://github.com/Foundation-19/Foundation-19/commit/84abb9f709ba1f6cef180f236a46eb046a64239d)
The following pull requests are currently test merged:
[#1258: '049 chamber botany' by K4rlox at commit ba9f8ce9bc](https://github.com/Foundation-19/Foundation-19/pull/1258)
[#1298: 'removes "lost" camera + admin bunker rename' by KirovClassBattlecruiser at commit 4639108a01](https://github.com/Foundation-19/Foundation-19/pull/1298)
[#1302: 'Adds automatic dir-facing on fire + a few balloon alerts + spellcheck' by cheesePizza2 at commit 7e31a66f0b](https://github.com/Foundation-19/Foundation-19/pull/1302)
[#1205: 'SCP Code Refactor' by TheDarkElites at commit 80a15e1c18](https://github.com/Foundation-19/Foundation-19/pull/1205)
[#1304: 'APC improvements' by cheesePizza2 at commit acc0a4cc5f](https://github.com/Foundation-19/Foundation-19/pull/1304)

Local commit: 6e0af8e52e62ad8bdef3f18f812f2c3a2930fed7
TGS version: 5.15.1
DMAPI version: 5.6.1

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
Unable to recreate on 11.03.24, operating computer displays information as intended for both monkeys and humans. 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/31a13813-4263-4f2f-9c6b-edd2d1628e8b)


The scanner does seem to have some text display issues but that could be because the markup code it's using are antiquidated, I'll let someone with more know-how address that. 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/9c79cff0-f1e2-41f5-a808-0a0bde0a5792)
