### ISSUE TITLE
player panel only lists humans

### ISSUE THREAD

**Issue by TheDarkElites** [Foundation-19/Foundation-19#1314]
#### Description of issue
Player Panel (the one that lists all players) only shows humans.

#### Difference between expected and actual behavior
This should show all living mobs with a ckey.

#### Steps to reproduce
press "Show Player Panel"

#### Specific information for locating
code/modules/admin/player_panel/player_panel.dm
line 197

#### Length of time in which bug has been known to occur
Eternity

#### Client version, Server revision & Game ID
Dosent Matter

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by 77seven77seven** [comment]
>[good first issue added by darkelites](https://i.imgflip.com/1hhv9m.jpg?a470961)

**Comment by TheDarkElites** [comment]
It literally says exactly where to do the fix, and all you have to do is change a type, and it is fixed. It literally cannot be easier than this, it isn't more than a single word long of a fix let alone a whole line.

**Comment by TerryTehCoder** [comment]
Unable to recreate on 10.03.24.

Tried with 2427, 049, mouse, cat, IPC, crab, monkey, unathi, and a Corgi, all showed up in the player panel with my Ckey. 

Likely resolved.
