### ISSUE TITLE
Donut box sprite

### ISSUE THREAD

**Issue by Lman154** [Foundation-19/Foundation-19#1360]
#### Description of issue

The donut box has not sprite when opened

#### Difference between expected and actual behavior

it should have a sprite

#### Steps to reproduce

just open the box

#### Specific information for locating

![image](https://github.com/Foundation-19/Foundation-19/assets/148709362/638d027f-5e96-414e-92f8-e1e6dd0644c5)

#### Length of time in which bug has been known to occur
 a couple rounds maybe longer

#### Client version, Server revision & Game ID

514.1585

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
I Didn't see this duplicate issue. Resolved in #1524.
