### ISSUE TITLE
scp173 cant interact with anything

### ISSUE THREAD

**Issue by whoisdeez** [Foundation-19/Foundation-19#1363]
#### Description of issue

cant interact (open door, break lights) as 173

#### Difference between expected and actual behavior

expected: break light not in my containment cell

actual: cant break light outside my containment cell

#### Steps to reproduce

1.ghost
2.scp173
3.bug

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by whoisdeez** [comment]
NVM IT WORKS

**Comment by aidan-bowman** [comment]
> NVM IT WORKS

then close the-

buhhhhhhhhhhhh

**Comment by whoisdeez** [comment]
> > NVM IT WORKS
> 
> then close the-
> 
> buhhhhhhhhhhhh

closing and rejoining didnt fix
i was between outside and my cell and it didnt give me any message about you cant open that door so i tought it was broken
