### ISSUE TITLE
ACS pencode for SCP articles

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1379]
[ACS explanation](https://scp-wiki.wikidot.com/anomaly-classification-system-guide)

Implement some way to generate ACS images, and add them to all SCP files.

**Comment by aidan-bowman** [comment]
Could use some ideas from the [S7-APCS](https://scp-wiki.wikidot.com/s7-apcs-guide) system if modification is desired.

**Comment by aidan-bowman** [comment]
https://scp-wiki.wikidot.com/component:anomaly-class-bar

ACS CSS code is here, in the page source code. It'll have to be appropriated to BYOND though.

**Comment by checkraisefold** [comment]
> https://scp-wiki.wikidot.com/component:anomaly-class-bar
> 
> ACS CSS code is here, in the page source code. It'll have to be appropriated to BYOND though.

actual component source is here
https://scp-wiki.wikidot.com/component:anomaly-class-bar-source
