### ISSUE TITLE
Move 294 to its own containment chamber

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1406]
294 (the vending machine that can output deadly neurotoxins and fucking antimatter) is right smack dab in the middle of the upper management offices. If I see ONE (1) more incompetent SD drinking 008 from this thing I'm gonna SCREAM

**Comment by TheDarkElites** [comment]
If only I knew how to map :(

**Comment by aidan-bowman** [comment]
> If only I knew how to map :(

it is so ridiculously easy

**Comment by TerryTehCoder** [comment]
This was completed in one of the mapping changes and requires closure. 
![image](https://github.com/user-attachments/assets/6dd359b0-57e5-4771-8281-ef62e09812e5)
