### ISSUE TITLE
borgs cannot view people's id on examine

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#1426]
#### Description of issue

tin

#### Difference between expected and actual behavior

![image](https://github.com/Foundation-19/Foundation-19/assets/19525688/63b36e5e-021d-461c-89d1-b8c8293215d7)

**Comment by checkraisefold** [comment]
fails default /mob can_see check because the ID on the person is not in view(7, src)

**Comment by Saicchi** [comment]
Duplicate https://github.com/Foundation-19/Foundation-19/issues/1370
