### ISSUE TITLE
Change the Wiki button to redirect to Baystation wiki instead of the hardly finished F19 Wiki

### ISSUE THREAD

**Issue by pumpkintheproot** [Foundation-19/Foundation-19#1488]
#### Description of issue

The official F19 wiki is.. very unfinished. Half the pages don't exist and only few useful guides are present. What I suggest is to change the Wiki button to the Baystation wiki, as this server is running on Baycode and would be better temporarily until the F19 wiki is finished for new players.

#### Difference between expected and actual behavior

Wiki > https://scp13.miraheze.org/wiki/Main_Page :( 👎 
Wiki > https://baystation.xyz/index.php?title=Main_Page :) 👍 

#### Steps to reproduce

Click wiki button?

#### Length of time in which bug has been known to occur

Forever, hopefully should only be changed until Wiki is either finished or usable

#### Client version, Server revision & Game ID

Round ID: csb-cxqM
BYOND Version: 514.1589
Server revision compiled on: 2024-02-04T21:19:41+00:00
Master commit: [0f7ee6c6516fc32faf544565257b6d8996bddb2f](https://github.com/Foundation-19/Foundation-19/commit/0f7ee6c6516fc32faf544565257b6d8996bddb2f)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by KingSuperBOB** [comment]
Don't the rules directly link to the wiki for further explanation, wouldn't replacing it cause issues.

**Comment by pumpkintheproot** [comment]
> Don't the rules directly link to the wiki for further explanation, wouldn't replacing it cause issues.

The rules is a different button to the Wiki, and it wouldn't cause issues because you could either check the Discord or hit the rules button
![image](https://github.com/Foundation-19/Foundation-19/assets/149212571/95934389-149e-4160-8783-08255838f6f2)
I'm pretty sure the Rules and Wiki button are seperately configured anyway

**Comment by DragonFire101** [comment]
The better option would be updating our wiki.
Care to volunteer?
As no one is working on the wiki at all.

**Comment by cheesePizza2** [comment]
This is an absolutely AWFUL idea, also you shouldn't even propose changes like that here.
