### ISSUE TITLE
Map atmos in

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#1519]
Alright, I know that at some point we planned to just remove atmos, buuuuut honestly I'd rather just map all the pipes back in than handle deleting all of that code.

Besides, I think we can use atmos for a few things.

**Comment by checkraisefold** [comment]
Atmos is the slowest subsystem by a long shot right now. Let's port auxmos :trollface:

**Comment by TerryTehCoder** [comment]
Atmos was reconstructed in the referenced #1588 with a few necessary systems. This needs closure.
