### ISSUE TITLE
#1514 causes the AIC to not be able to access any of their HUD buttons and prevents a majority of their procs from being added to Silicon Commands. 

### ISSUE THREAD

**Issue by TerryTehCoder** [Foundation-19/Foundation-19#1522]
#### Description of issue

#1514 (among other things) converted the verb list of the AIC from written out procs in the verb list to using TYPE_PROC_REF.
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/824a1e09-d161-417e-9a26-402bd58b2086)
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/5cadfe34-2f7c-4fec-a16b-5bf17d79ceb3)

This (for reasons beyond me) caused the majority of the AIC's verbs to not be added to the Silicons Command tab, it also appears to have affected the AIC Hud as none of the HUD buttons do anything when clicked on. 

This runtime is given when the code is compiled normally: 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/89142410-bcec-4b2f-aec8-2129dced7efb)
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/6b78421f-ef1d-4d0f-a6a3-1b89b8e524ee)

Verb List and Silicon Commands tab when code is compiled as normal: 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/4f920cf9-22a4-4c64-b9e9-03f138872ff8)

It's worth noting that the "Take Image" verb is setup in a completely different place, as well as "View Images", "Delete Images", and "Subsystems", none of them actually setup as Procs. 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/64807e77-e96f-4871-9c26-957d0bc4e961)

All of the verbs and functionality of the HUD buttons return when TYPE_PROC_REF is replaced with just the old procs in the list. The runtime is no longer present when the verbs are changed to the old list.

It's possible this has affected other verb list as well although I haven't run into any. 

#### Difference between expected and actual behavior

Expected: HUD Buttons function and the A.I has access to all of its verbs.

Actual: HUD Buttons do not function and the A.I has access to roughly four verbs, none of which are from the A.I Folder itself. 

#### Steps to reproduce

Begin a round as AIC, inspect Silicon Commands (Find Four Verbs Present), Click HUD Buttons.

#### Length of time in which bug has been known to occur

Unknown. Since #1514 has been test-merged? So maybe a day? It was merged fully 53 minutes ago. 

#### Client version, Server revision & Game ID

515.1633
Unknown, tested on local client after fresh copy. 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [Untested] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by TerryTehCoder** [comment]
The verbs fully populate the Silicon Commands tab when the list is moved back to the old style. 
![image](https://github.com/Foundation-19/Foundation-19/assets/78599370/109e76f9-f921-4893-8705-8624630a3567)

**Comment by Tsurupeta** [comment]
I thought I fixed that before merging it in huh

**Comment by Tsurupeta** [comment]
Yeah, I fixed that before merging PR in.

**Comment by TerryTehCoder** [comment]
Lovely dovely. I'll close this issue then. Hard to see on the last commit and I wasn't sure if it had been dealt with, my mistake.

**Comment by Tsurupeta** [comment]
I am still not sure if interface buttons work.

**Comment by TerryTehCoder** [comment]
I've encountered no issues with this since it was fixed, but let me know if it's ready to be closed or you're still looking into some aspects of it.
