### ISSUE TITLE
Changelings can turn them selfs into humanoid SCPS.

### ISSUE THREAD

**Issue by DragonFire101** [Foundation-19/Foundation-19#1627]
#### Description of issue

Changelings can turn them selfs into humanoid SCPS such as 106 and 049 and etc.

#### Difference between expected and actual behavior

Not to have changelings to able to become any SCP.

#### Steps to reproduce
Changling sting a SCP then transform into them.
#### Specific information for locating

Changeling Antag

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Round ID: cs2-agk8
BYOND Version: 515.1633
Server revision compiled on: 2024-03-31T15:19:45+00:00
Master commit: [0547aed593e5e551e5cc3ba8927102cbf9955a4f](https://github.com/Foundation-19/Foundation-19/commit/0547aed593e5e551e5cc3ba8927102cbf9955a4f)
The following pull requests are currently test merged:
[#1561: 'Energy Net Changes' by tichys at commit f388e0922f](https://github.com/Foundation-19/Foundation-19/pull/1561)
[#1578: 'Adds override for timelocks for roles already played' by TheDarkElites at commit 600c07decd](https://github.com/Foundation-19/Foundation-19/pull/1578)
[#1570: 'LCZ Division Adjustments (And some required fixes)' by ChromeFoxxity at commit 5de732084d](https://github.com/Foundation-19/Foundation-19/pull/1570)
[#1179: 'Observables -> Signals' by cheesePizza2 at commit 7e20389bcf](https://github.com/Foundation-19/Foundation-19/pull/1179)
[#1598: 'AIC access area apc' by Saicchi at commit 4bb410b65a](https://github.com/Foundation-19/Foundation-19/pull/1598)
[#1615: 'Soap update' by chesse20 at commit dc69b3fd79](https://github.com/Foundation-19/Foundation-19/pull/1615)

Local commit: 920cb0932d4e94269a6f46019c81a05def9c829e
TGS version: 6.4.0
DMAPI version: 5.6.1

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by checkraisefold** [comment]
INSANE bug

**Comment by chesse20** [comment]
looks like emergent gameplay to me
