### ISSUE TITLE
D-Class mines rather commonly spawn anomalies that kill half the server with radiation leaks.

### ISSUE THREAD

**Issue by Bamhalazam** [Foundation-19/Foundation-19#165]
#### Description of issue
Read title.

#### Difference between expected and actual behavior
The entirety of the site Z-level and beyond gets irradiated due to the artifact applying a radiation effect to anyone within a Z-level

#### Steps to reproduce
Mine in D-blocks.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Since dawn of man (and F19)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Ben10083** [comment]
From what I can tell the supermatter shards have been removed as a possibility for artifacts, are you still able to replicate this?

**Comment by Ben10083** [comment]
Fixed by #214
