### ISSUE TITLE
Everytime someone opens the orbit menu each name duplicates

### ISSUE THREAD

**Issue by ChuChu42** [Foundation-19/Foundation-19#1704]
#### Description of issue
as the title says, orbit menu is buggy

#### Difference between expected and actual behavior
each name to show up once is expected
instead, everytime someone opens the menu, the names duplicate, most of them dont even work

#### Steps to reproduce
1. ghost
2. spawn a mob
3. open orbit menu
4. close
5. open again
6. mob (3)
7. repeat
8. mob (4)

#### Length of time in which bug has been known to occur

since the new orbit menu was added

#### Client version, Server revision & Game ID

Round ID: cus-cqUA
BYOND Version: 515.1636
Server revision compiled on: 2024-06-29T12:49:27+00:00
Master commit: [ce5dc348766b9b31d17385ef803d58298d3ce9a3](https://github.com/Foundation-19/Foundation-19/commit/ce5dc348766b9b31d17385ef803d58298d3ce9a3)
The following pull requests are currently test merged:
[#1596: '294 updates' by TheDarkElites at commit 0ffec973d8](https://github.com/Foundation-19/Foundation-19/pull/1596)
[#1691: 'job fix 2' by quadbium at commit 2815212f6f](https://github.com/Foundation-19/Foundation-19/pull/1691)
[#1698: 'Self-Destruct authentication updates' by TerryTehCoder at commit 5c00d9218f](https://github.com/Foundation-19/Foundation-19/pull/1698)
[#1641: 'ports nebula weather' by tichys at commit 8fb5f710f1](https://github.com/Foundation-19/Foundation-19/pull/1641)
[#1701: 'R-UST fixes' by checkraisefold at commit 13c7766a58](https://github.com/Foundation-19/Foundation-19/pull/1701)
[#1697: 'Map & Icon Adjustments' by ChromeFoxxity at commit 35561e5dfb](https://github.com/Foundation-19/Foundation-19/pull/1697)
[#1703: 'Loadout & Vendor Changes' by projectkepler-ru at commit ceb73e2dc9](https://github.com/Foundation-19/Foundation-19/pull/1703)

Local commit: 98816e878169e827ea37bdf73b932e2ea5218ac9
TGS version: 6.4.0
DMAPI version: 5.6.1

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by ChuChu42** [comment]
additionally pressing X or cancel in the orbit menu sends you to the void

**Comment by checkraisefold** [comment]
closed by #1695

**Comment by islaughterfunny** [comment]
just remove orbit all together, clicking it with anymore then 5 players lags the game out since it has to find every single mob

**Comment by checkraisefold** [comment]
> just remove orbit all together, clicking it with anymore then 5 players lags the game out since it has to find every single mob

it solely lags out because of shitcode and it will be fixed

**Comment by islaughterfunny** [comment]
> > just remove orbit all together, clicking it with anymore then 5 players lags the game out since it has to find every single mob
> 
> it solely lags out because of shitcode and it will be fixed

remove it untill its fixed then
