### ISSUE TITLE
Bug: engineering augment tools can be dropped

### ISSUE THREAD

**Issue by Tsurupeta** [Foundation-19/Foundation-19#175]
Nature of Bug: You can drop tools from the engineering augment, which will remove them from your augment until you pick them back up and retract them again
Effect on Gameplay: It's like a bugged toolbelt in your wrist, but stupid
Steps to Reproduce, if any: Use augment, press Q, watch in awe

![image](https://user-images.githubusercontent.com/41485301/177547485-8da9dd3a-4129-4eda-a5b2-55043755a1f0.png)

[copied from discord](https://discord.com/channels/896489363599417345/896489960394358804/994210210136731661)

**Comment by 77seven77seven** [comment]
cant this just be fixed by setting 'can_remove = FALSE' on the items...?

**Comment by checkraisefold** [comment]
cannot reproduce/not enough info, doesnt seem to happen
