### ISSUE TITLE
Runtime: timer.dm, line 460: type mismatch

### ISSUE THREAD

**Issue by Tsurupeta** [Foundation-19/Foundation-19#191]
Runtime in timer.dm, line 460: type mismatch: cannot compare /mob/living/simple_animal/host... (/mob/living/simple_animal/hostile/scp096/proc/reduce_examine_urge) to 0

**Comment by aidan-bowman** [comment]
Runtimes like this come from incorrectly using addtimer(). Looking through the code, it seems like this specific one is fixed. Issue can probably be closed now.
