### ISSUE TITLE
BUG:scps can get shrapnels in them

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#207]
#### Description of issue
SCP 49, SCP 106 and (not exactly a bug but still)49-1 instances do not have SPECIES_FLAG_NO_EMBED (get fucked when stepping on glass and can get shrapnel embedded in their ass)

#### Steps to reproduce
shoot a SCP and be lucky, they can't heal themselfs from it so yeah... they are fucked

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by 77seven77seven** [comment]
i might start work on this

**Comment by 77seven77seven** [comment]
SCP-049-1 instances are still humans, so they won't receive the flag.

**Comment by 77seven77seven** [comment]
oke anyway this is fixed close this
