### ISSUE TITLE
BUG:SCP 500 is buggy

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#222]
#### Description of issue
SCP 500 sometimes will simply not restart the person's heart, it also doesn't remove pain (i learned that the hard way by having a heart attack)

SCP 500 (APPARENTLY) deletes synthetic organs, i have not tested this yet, but it was reported on discord
#### Difference between expected and actual behavior
SCP 500 heals everything

SCP 500 doesn't heal everything
#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by projectkepler-ru** [comment]
this seem to be fixed(?) as it now properly aheal and revive people

**Comment by aidan-bowman** [comment]
> this seem to be fixed(?) as it now properly aheal and revive people

If this is fixed, can someone close the issue?

**Comment by 77seven77seven** [comment]
its been a fucking year can any of you close this already
