### ISSUE TITLE
New spawning with some of your equipment.... smh

### ISSUE THREAD

**Issue by LoganKele** [Foundation-19/Foundation-19#224]
#### Description of issue
Due to the new update, you spawn with /some/ not all of your equipment.
You know those loadout items as well? you do not get them.

#### Steps to reproduce
pick loadout stuff
spawn in

#### Client version, Server revision & Game ID

514
[a0a2e28c58faffe48f62d054274447eb7369751e](https://github.com/Foundation-19/Foundation-19/commit/a0a2e28c58faffe48f62d054274447eb7369751e)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by aidan-bowman** [comment]
this issue seems extremely non-descriptive, either someone needs to elaborate what the issue is or this should get closed.
