### ISSUE TITLE
Concealable Augmentations "Damaged" Bug

### ISSUE THREAD

**Issue by MrBobCool** [Foundation-19/Foundation-19#227]
#### Description of issue
Concealable blade/shotgun augmentations from traitor PDA uplink break and won't redeploy/they become dropable objects.

#### Difference between expected and actual behavior
Once you use the shotgun augmentation or the blade augmentation on someone, they suddenly break. You'd expect it to continue working normally.

#### Steps to reproduce
Use your new shotgun augmentation or the blade augmentation on someone, it breaks, try to conceal it, message pops up "The device is damaged and fails to deploy"

#### Specific information for locating

"The device is damaged and fails to deploy"
Shotgun arm augmentation, blade arm augmentation/wrist blade whatever.

#### Length of time in which bug has been known to occur

Forever? Idfk

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [353aa23a9557e3c61325f5ed53874d69cd484445](https://github.com/Foundation-19/Foundation-19/commit/353aa23a9557e3c61325f5ed53874d69cd484445) - main - 2022-07-09
Game ID: ciP-a3FK
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by reklaw9** [comment]
apparently someone is fixing this already

**Comment by checkraisefold** [comment]
cannot reproduce assumed fixed
