### ISSUE TITLE
The HRO has no access to open his locker

### ISSUE THREAD

**Issue by BadAtThisGame302** [Foundation-19/Foundation-19#231]
#### Description of issue
The HRO can't open his locker

#### Difference between expected and actual behavior
The HRO should be able to open his locker

#### Steps to reproduce
Be HRO, try to open your locker

#### Specific information for locating
Join as HRO

#### Length of time in which bug has been known to occur
Since the addition of the HRO locker?

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: [216e9aa6471934f0c5bbb052b5d2ded1799e8b39](https://github.com/Foundation-19/Foundation-19/commit/216e9aa6471934f0c5bbb052b5d2ded1799e8b39) - main - 2022-07-09
Game ID: ciP-bCY9

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Bierkraan** [comment]
Looking into it
