### ISSUE TITLE
BUG:some amnestics have wrong classifications.

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#256]
#### Description of issue
Class A amnestics:
entire round, 6-8 hours, specially effective for PTSD and episodic shit.
**CURRENT DESCRIPTION:**
"Your memories are melting away... You will not be able to remember the events leading up to your amnesticization."

Class B AMNESTICS:
6 hours to one day, dependent on dosage, overdose treshhold kinda high, full amnestization.
**CURRENT DESCRIPTION:**
"Your memories of the day are melting away... You have lost all memory up until the point when the round began"

Class C amnestics:
surgical/magic procedure where a doctor removes a knowledge or specific stuff from someone's brain/mind using a specific reagent + THE POWER OF... technology, takes a long time, pretty low failure rate compared to other amnestics.
**CURRENT DESCRIPTION:**
"Your memories of the past week are melting away... You are free to come up with any RP for what you were doing a week ago."

Class D amnestics:
much more potent than other amnestics, able to delete all memories from the user if used  incorrectly, **deletes the oldest memories first before, at the end only deleting new memories**, extremely dangerous.
**CURRENT DESCRIPTION:**
"Your memories of the past several weeks are melting away... You are free to come up with any RP for what you were doing a few weeks ago"

CLASS F AMNESTICS:
deletes all memories involving the user's personality, does not delete other memories like skills or knowledge unless paired up with other amnestics.
**CURRENT DESCRIPTION:**
"All your memories are melting away... You have lost every memory you hold dear and every aspect of your identity has been torn away to be re-modelled like clay"

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by reklaw9** [comment]
amnestics guide:

https://scp-wiki.wikidot.com/updated-amnestics-guide

**Comment by aidan-bowman** [comment]
This should be closed since I overhauled amnestics.
