### ISSUE TITLE
HR Offical can't modify ID's or access their own locker

### ISSUE THREAD

**Issue by Thegodemperorofmankind11** [Foundation-19/Foundation-19#315]
## Description
The Human Resources Official, Can't Modify ID's and also can't access their own locker

## Difference between expected and actual behaviour
The Human Resources Official, is the HoP for F19, and should be able to Modify IDs, or access their own locker.

## Steps to reproduce
Try Opening your own locker, and then trying to Modify your ID to open it. 

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MrBobCool** [comment]
Tested, ID works fine both as a Head of Personnel and a Human Resource Official for giving IDs access and unlocking your locker. My guess is someone fixed this without closing this issue.

Requesting this closed.
