### ISSUE TITLE
Power going out severely lags the server

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#318]
## Description
Because of how much shit is on the map, machines and lighting subsystems start using the entire CPU whenever a power outage event occurs. The event should be removed from rotation.

Also restrict admins from using it since the latest crash was from an admin triggering it manually.

**Comment by Vivalas** [comment]
How long does the lag last / do you have logs of a crash occurring after using it? It should lag for a short period after firing, that's normal

**Comment by checkraisefold** [comment]
> How long does the lag last / do you have logs of a crash occurring after using it? It should lag for a short period after firing, that's normal

A few rounds ago the power off event brought the machines subsystem to 13,000 ms like 4 minutes later and the server had to be reset. I don't have logs from the main server.

**Comment by checkraisefold** [comment]
Server is severely lagging again from an admin doing this again.

**Comment by checkraisefold** [comment]
Staff are griefing the server with this. Server just crashed another round in a row.

**Comment by checkraisefold** [comment]
Someone at bay thought it would be a good idea that every time the APC failure timer ticks down by 1 second to call apc update() which calls area power_change which loops through thousands of machines a second
Patch imminent
