### ISSUE TITLE
247 Tranquilizer Storage has an empty dispenser and lacks reserve tranquilizer agents

### ISSUE THREAD

**Issue by Derpguy3** [Foundation-19/Foundation-19#331]
## Testmerges:
Server was down and I was unable to check.

## Description

The equipment in 247's tranquilizer storage is lacking a reserve of pre-mixed chemicals (which used to be a large cartridge of chloral hydrate), and the chemical dispenser is unable to dispense any chemicals as it lacks any cartridges. Normally you could get cartridges to fix this, but due to the recent removal of all cartridges, this cannot happen.
It is likely this was a result of the removal of all of the chemical cartridges.
## Difference between expected and actual behavior

There should be a working dispenser, and premixed tranquilizers (previously chloralhydrate) in reserve ready to use.

## Steps to reproduce

Go into tranquillizer storage and interact with the chemical dispenser and see the lack of premixed tranquilizer.
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Vizoplez** [comment]
As far as I'm aware this was changed/removed specifically because HCZ guards were powergaming the shit out of the syringe guns (since the ones in there were reskinned Vox guns, and went through armor)

And the fact that 247 still lacks correct mob processing for sedatives to actually work

**Comment by checkraisefold** [comment]
this specifically is fixed, HOWEVER 247 has no chemical processing and as such the sedatives will do nothing
i will make a separate issue or just fix it now
