### ISSUE TITLE
NT Net repair bug

### ISSUE THREAD

**Issue by Synde45** [Foundation-19/Foundation-19#374]
#### Description of issue

NT Net (aka. internet) Once destroyed or down cannot be fixed, repaired, or rebuilt.

#### Difference between expected and actual behavior

When destroyed, damaged, etc. It should be back up and working just fine. Instead, it simply remains down and cannot be fixed. In one round it was rebuilt six times and still failed.

#### Steps to reproduce

Destroy NT NET server/array and attempt to rebuild/repair it.

#### Length of time in which bug has been known to occur

Once the NT NET is destroyed it cannot be fixed in-game.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [629697352b234564ed1401d9082c33f56fc837f6](https://github.com/Foundation-19/Foundation-19/commit/629697352b234564ed1401d9082c33f56fc837f6) - main - 2022-07-13
Game ID: ciT-dD12
Current map: Foundation Site 53

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by checkraisefold** [comment]
unable to reproduce whatsoever
