### ISSUE TITLE
Various issues with Guard gear inconsistencies

### ISSUE THREAD

**Issue by Zilenan** [Foundation-19/Foundation-19#386]
Making this because I got told to by Vivalas

#### Description of issue
Guards of all kinds are missing a bunch of items either on spawn, or in their equipment rooms such as:

Sechuds for LCZ Guards
Crowbars for LCZ and HCZ Guards
HCZ Guards need a bigger Equipment room in general
Arm + Leg coverings for the modular armor Plate Carriers that both LCZ Guards and EZ Agents get in their lockers/on spawn
HCZ Guards need Arm + Leg coverings for their modular armor spares in their lockers as well
EZ Guards lack first aid boxes in their lockers

#### Difference between expected and actual behavior

They should have these items

#### Steps to reproduce

Spawn

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [629697352b234564ed1401d9082c33f56fc837f6](https://github.com/Foundation-19/Foundation-19/commit/629697352b234564ed1401d9082c33f56fc837f6) - main - 2022-07-13
Game ID: ciU-a1vN
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ItsVyzo** [comment]
- [ ] Sechuds for LCZ Guards
- [x] Crowbars for LCZ and HCZ Guards
- [x] HCZ Guards need a bigger Equipment room in general
- [ ] Arm + Leg coverings for the modular armor Plate Carriers that both LCZ Guards and EZ Agents get in their lockers/on spawn
- [ ] HCZ Guards need Arm + Leg coverings for their modular armor spares in their lockers as well
- [x] EZ Guards lack first aid boxes in their lockers

**Comment by ItsVyzo** [comment]
The rest should be implemented via code. Extra Arm/Leg covering will probably not be added. There are too many things in the lockers already IMHO but it's up to the coder.

**Comment by ItsVyzo** [comment]
@Vivalas

**Comment by projectkepler-ru** [comment]
this is now resolved.
