### ISSUE TITLE
A large amount of doors do not have access requirements when they should

### ISSUE THREAD

**Issue by Zilenan** [Foundation-19/Foundation-19#395]
#### Description of issue

Many doors around the map do not have access requirements that probably should. Basically every door in ULCZ, especially the ones that allow you further into the hallways needs to get looked at because you don't need any kind of access whatsoever to open them, same with areas of D-block that should be restricted such as chemistry (which shouldn't even exist down there) and medical as a whole.

HCZ also has a bunch of doors that do not have access requirements but should, such as the door leading from the checkpoint at the tram into the office in the back, the door itself is called the "Heavy Containment Zone Gate Security Post". The doors to transit between each SCP also similarly have no access requirements.

I'll update this later with EZ doors

#### Difference between expected and actual behavior

Movement should be more restricted to those with access.

#### Steps to reproduce

Open the doors

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by TopHatPenguin** [comment]
Adding onto this report:

Office workers can access logistics and order items.

**Comment by projectkepler-ru** [comment]
massive oversight.. should be fixed on dev branch now

**Comment by TerryTehCoder** [comment]
The map has seen major revisions since this issue was opened, such as the entire removal of the Trams, checkpoint redesigns, integration of logistics into the site, etc. I suggest closing it and if this issue still exists for a large quantity of airlocks a new issue should be made with up to date information. This is two years old.
