### ISSUE TITLE
Dboys can open apcs

### ISSUE THREAD

**Issue by GaboPache** [Foundation-19/Foundation-19#404]
#### Description of issue
Essentially, dboys can open apcs if they use their ids on them, so yea

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Vizoplez** [comment]
This was due to a developer breaking all access requirements in the DCZ area.
