### ISSUE TITLE
Airlock circuit UI broken

### ISSUE THREAD

**Issue by AC2ServerAccount** [Foundation-19/Foundation-19#412]
#### Description of issue
Airlock circuit UI is broken, have a gif.
https://gyazo.com/18905fa7823188f8b2defceaa50f3659

#### Difference between expected and actual behavior
Click on access level, expect it to check, it doesnt check.

#### Steps to reproduce
Get airlock circuit, unlock, click things.

#### Specific information for locating

Airlock circuit

#### Length of time in which bug has been known to occur

Unknown 

#### Client version, Server revision & Game ID

[5dc1a2344224c08e0d28e508905018c30e367a4d](https://github.com/Foundation-19/Foundation-19/commit/5dc1a2344224c08e0d28e508905018c30e367a4d) - main - 2022-07-14
Game ID: ciU-djoQ

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Goodfishie** [comment]
Confirming that this happens.

I've double checked what the map's spawned circuits use and it appears that, for instance

to use an engineering door you need "Engineering Level 1" Access. this is visible on the circuit, but you are unable to click on or make any changes to it.

This means that it is functionally impossible to make restricted doors because all of the access levels you need to use are unusable

**Comment by AC2ServerAccount** [comment]
> Confirming that this happens.
> 
> I've double checked what the map's spawned circuits use and it appears that, for instance
> 
> to use an engineering door you need "Engineering Level 1" Access. this is visible on the circuit, but you are unable to click on or make any changes to it.
> 
> This means that it is functionally impossible to make restricted doors because all of the access levels you need to use are unusable

I dont think player made windoors in general even work, I made one and flat out couldnt interact with it but havent had a chance to try and reproduce it

**Comment by checkraisefold** [comment]
This is mostly fixed and more fixes pending
