### ISSUE TITLE
Escape train doesn't actually depart

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#420]
#### Description of issue

Escape train is just in the station the whole game, doesn't actually leave the station even after ETD has ended

#### Difference between expected and actual behavior

Expected: Escape train departs, allowing personnel to escape the rampant containment breaches
Actual: it sits there

**Comment by checkraisefold** [comment]
please fix this

**Comment by projectkepler-ru** [comment]
this likely won't get fixed as the map intends to be replaced entirely
