### ISSUE TITLE
Ladders are broken

### ISSUE THREAD

**Issue by jmlop0** [Foundation-19/Foundation-19#440]
#### Description of issue
Ladders don't work

#### Difference between expected and actual behavior
Expected: Ladders working
Actual: Ladders not working when at the bottom of them.

#### Steps to reproduce

Attempt using a ladder from the bottom part.

#### Specific information for locating

Ladder (So far the one in the maintenance to the wilderness next to the Emergency Bunker, and apparently the one at 106.

#### Length of time in which bug has been known to occur

Not sure.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [bc8c6baba9274e4e8fb9a3362cbff6efa85583d0](https://github.com/Foundation-19/Foundation-19/commit/bc8c6baba9274e4e8fb9a3362cbff6efa85583d0) - dev - 2022-07-15
Game ID: ciW-aaxX
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ItsVyzo** [comment]
Fixed by @Vivalas
