### ISSUE TITLE
BUG: 49 still can't deathtouch people

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#442]
#### Description of issue
49 still can't deathtouch people that were infected by the pestilence

#### Difference between expected and actual behavior
hes 49, hes dangerous bro... he can kill with a single touch

hahahaha, beat doctor with sticc
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Vizoplez** [comment]
This isn't a bug but intended game balance.

049 has had PRs up that re-adds it.

**Comment by ghost** [comment]
The balance is in the SCP lore, the body part he touches has to be unclothed. You negate him by wearing full armor, or a bio-suit.
