### ISSUE TITLE
BUG - Multiple jobs can perform logi tasks invalidating the logi roles

### ISSUE THREAD

**Issue by TopHatPenguin** [Foundation-19/Foundation-19#464]
#### Description of issue
Title.

#### Difference between expected and actual behavior
Logi should only be doable by logi and heads of staff (emergency)

#### Steps to reproduce
- be EZ
- be D Class
- be Office worker
- Perform logi
- approve/deny orders
- call the supply heli
- profit

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by TopHatPenguin** [comment]
May also want to check if anybody else can, for example office workers have full access to logistics. So it's likely they also can approve order and run logi.

**Comment by TopHatPenguin** [comment]
So just checked and yeah, Office workers and D class can both approve and deny logistics as they have the same access levels. This means you can have a logi war with a D class on a laptop all the way in DCZ.

**Comment by Vizoplez** [comment]
> So just checked and yeah, Office workers and D class can both approve and deny logistics as they have the same access levels. This means you can have a logi war with a D class on a laptop all the way in DCZ.

incredibly funny but as far as I'm aware also originates due to people fucking up d-class access (again) and the fact the logi program doesn't handle this very well.

Similar issue to earlier today when all ID consoles broke before the mapfix a few hours ago.

**Comment by hry-gh** [comment]
not currently able to replicate this on dev branch, probably been sorted in the meantime

**Comment by projectkepler-ru** [comment]
this issue has been resolved on the dev branch. also EZ agent cant call supply heli for awhile now.
