### ISSUE TITLE
BUG: 173 can kill people while being looked at

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#466]
#### Description of issue

**NPC** 173 can kill people when being looked at, even if over 6 people are looking at it

#### Difference between expected and actual behavior
173 cant move while 6 people are looking at it

now 5 people are looking at it
#### Steps to reproduce
test NPC 173

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by projectkepler-ru** [comment]
there seems to be an odd bug with the line of sight where if 173 only recently come into views it will still be mobile
this also apply to when its in cage and just left it. unsure how this could be fixed

**Comment by TheDarkElites** [comment]
This no longer occurs after #1116
