### ISSUE TITLE
BUG: Eyesquishing doesn't work

### ISSUE THREAD

**Issue by Pyrodes** [Foundation-19/Foundation-19#473]
#### Description of issue

Eyesquishing doesn't work

#### Difference between expected and actual behavior

When you go through the steps needed to do it, you can only dislocate the jaw and not eyesquish.

#### Steps to reproduce

Grab and upgrade, target eyes with harm intent and click on target.

#### Length of time in which bug has been known to occur

Since at least a week ago

#### Client version, Server revision & Game ID

Client version: 514

Server revision: [0f6e49652619820c9e1892fcdfae06fad97e27c3](https://github.com/Foundation-19/Foundation-19/commit/0f6e49652619820c9e1892fcdfae06fad97e27c3) - dev - 2022-07-17

Game ID: ciX-duck

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Calyxman** [comment]
This has worked for me before, are you sure you're doing it correctly?

**Comment by Pyrodes** [comment]
> This has worked for me before, are you sure you're doing it correctly?

Well, I've used pretty much every possible combo to do it and it usually just tries to dislocate the jaw. If you know of a way that actually works currently please tell me as nothing so far has worked for me.

**Comment by checkraisefold** [comment]
i dont know what this means we dont have eye squishing in the code base
