### ISSUE TITLE
BUG: containment engineer doesnt have containment access

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#491]
#### Description of issue
containment engineer doesnt have the access to most SCPs

#### Difference between expected and actual behavior
containment engineer can access containment rooms

nahhh
#### Steps to reproduce
exist

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by aidan-bowman** [comment]
duplicate issue (see #223)
