### ISSUE TITLE
HCZ Camera networks are in the wrong networks/not connected to a network

### ISSUE THREAD

**Issue by Derpguy3** [Foundation-19/Foundation-19#502]
#### Description of issue
A number of cameras within the HCZ's camera network are in the incorrect place. There's a number of HCZ zone cameras that are in the LCZ's network, and there are LCZ zone cameras in the HCZ's network.
In addition, the cameras within 247's containment area do not appear to be connected to any of the networks.

#### Difference between expected and actual behavior
HCZ cameras should be in the HCZ Network, LCZ cameras in the LCZ Network.
247's cameras should be connected to a network.

#### Steps to reproduce
Examine the camera lists of both the HCZ and LCZ networks, and look for cameras in 247's containment.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Unknown, likely when some map changes occurred.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [302271b188fcc9d2d20638989931c2c9d524b3ab](https://github.com/Foundation-19/Foundation-19/commit/302271b188fcc9d2d20638989931c2c9d524b3ab) - dev - 2022-07-19
Game ID: ci1-atVA
#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by projectkepler-ru** [comment]
this has been on going for a bit now but I don't think anyone ever bothered to fix t
