### ISSUE TITLE
Cremator in SCP-008's freezer room is facing the wrong way

### ISSUE THREAD

**Issue by Derpguy3** [Foundation-19/Foundation-19#507]
#### Description of issue
The cremator in the freezer room in SCP-008's chamber is facing the wall and because of this, it cannot open, which means it cannot be used to cremate corpses.

#### Difference between expected and actual behavior
The cremator tray should be accessible.

#### Steps to reproduce
Try to open the cremator in the freezer room.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Likely since SCP-008's chamber was redesigned.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [e74769436b7967f2cb7c7857a3bbdbf3f7a67eb4](https://github.com/Foundation-19/Foundation-19/commit/e74769436b7967f2cb7c7857a3bbdbf3f7a67eb4) - dev - 2022-07-20
Game ID: ci2-ag4E

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ItsVyzo** [comment]
fixed
