### ISSUE TITLE
AIC can see ghosts.

### ISSUE THREAD

**Issue by Evie139** [Foundation-19/Foundation-19#514]
#### Description of issue
AIC is able to see ghosted characters while it is alive.

#### Difference between expected and actual behavior
Ghosts are unseen to the living normally.

#### Steps to reproduce
Spawn as AIC, observe ghosts.

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
Unsure.

#### Client version, Server revision & Game ID
Client version unknown (reported by two separate players)
server rev [eeab1a21710c1a65142efd3862c61e761ec55e76](https://github.com/Foundation-19/Foundation-19/commit/eeab1a21710c1a65142efd3862c61e761ec55e76) - dev - 2022-07-21
game ID ci2-b30P

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by TerryTehCoder** [comment]
This was fixed in #746 I believe?

Would be good to recheck.
