### ISSUE TITLE
Combat hazmat suit + helmet on mob sprite broken

### ISSUE THREAD

**Issue by BadAtThisGame302** [Foundation-19/Foundation-19#530]
#### Description of issue

When you wear the combat hazmat helmet or the suit on your person it appears as "SUIT" in green letters, also turning you naked

#### Difference between expected and actual behavior

...Guess

#### Steps to reproduce

Wear combat hazmat armor

#### Specific information for locating

Combat Hazmat Armor

#### Length of time in which bug has been known to occur

I have no clue, probably since the addition of the item

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [756ac01533a8a08bc9e24adc275fabe6821a6a4b](https://github.com/Foundation-19/Foundation-19/commit/756ac01533a8a08bc9e24adc275fabe6821a6a4b) - dev - 2022-07-22
Game ID: ci3-dl5A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Vivalas** [comment]
Aware of this at the moment, there was an issue with the fix PR and now we gotta wait until a larger merger is pushed through.
