### ISSUE TITLE
Airlock boards do not open UI when clicked on

### ISSUE THREAD

**Issue by ornkat** [Foundation-19/Foundation-19#541]
#### Description of issue
Airlock boards do not open UI when clicked on, which would normally allow you to set access levels.  I gave the electronics board in game to other people and the UI would not come up for them either.  No white screen, nothing shows up at all, even with my skills maxed out.  

#### Difference between expected and actual behavior
Normally a UI shows up and a couple of times now it does not show up when I click on the item

#### Steps to reproduce
Get an airlock board in game- click on it and see if it pulls up a UI

#### Specific information for locating

item is called "airlock board"

#### Length of time in which bug has been known to occur

A couple days- Wednesday (7/20) night I played and could not access UI, did AHELP and admin was confused.  Today (7/23) still having the issue.

#### Client version, Server revision & Game ID

Client version: 514
Server Revision: [756ac01533a8a08bc9e24adc275fabe6821a6a4b](https://github.com/Foundation-19/Foundation-19/commit/756ac01533a8a08bc9e24adc275fabe6821a6a4b) - dev - 2022-07-22
Game ID: ci4-bMm3

#### Issue bingo

- [X ] Issue could be reproduced at least once
- [ X] Issue could be reproduced by different players
- X[ ] Issue could be reproduced in multiple rounds
- [X ] Issue happened in a recent (less than 7 days ago) round
- [X ] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by checkraisefold** [comment]
#536 
this is fixed
