### ISSUE TITLE
You can die at any point without any reason if you hit succumb with cybernetic organs

### ISSUE THREAD

**Issue by Vizoplez** [Foundation-19/Foundation-19#545]
#### Description of issue
Title

#### Difference between expected and actual behavior
Succumbing at 100% HP with zero warning or confirmation should not be possible

#### Steps to reproduce
just click succumb with a cyber heart

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by checkraisefold** [comment]
https://github.com/Foundation-19/Foundation-19/blob/dev/code/modules/mob/living/carbon/human/human_defense.dm#L535
ladies and gentlemen, baycode
(cybernetic hearts have no pulse)

replace this with a check for heart is_working() https://github.com/Foundation-19/Foundation-19/blob/dev/code/modules/organs/internal/heart.dm#L196

**Comment by Vizoplez** [comment]
> https://github.com/Foundation-19/Foundation-19/blob/dev/code/modules/mob/living/carbon/human/human_defense.dm#L535 ladies and gentlemen, baycode (cybernetic hearts have no pulse)
> 
> replace this with a check for heart is_working() https://github.com/Foundation-19/Foundation-19/blob/dev/code/modules/organs/internal/heart.dm#L196

I still find this incredibly funny to this day
