### ISSUE TITLE
Modified Gas Mask does not work

### ISSUE THREAD

**Issue by chesse20** [Foundation-19/Foundation-19#571]
#### Description of issue

The modified gas mask does not change your voice or disguise your face

#### Difference between expected and actual behavior

It should change your voice and diguise your face to the id you are using

#### Steps to reproduce

buy modified gas mask as traitor

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by hry-gh** [comment]
baycode gas mask needs the name setting using the verb "set voice" then "toggle voice changer", is working on my local

**Comment by chesse20** [comment]
ah so its just bad ui
