### ISSUE TITLE
Forensics robot can't use its autopsy scanner

### ISSUE THREAD

**Issue by AC2ServerAccount** [Foundation-19/Foundation-19#580]
#### Description of issue

Some idiot bay coder made it so autopsy scanners can only be used by humans.

#### Difference between expected and actual behavior

Autopsy scanner to work, it rudely tells me no

#### Steps to reproduce

Forensics borg, autopsy scanner

#### Length of time in which bug has been known to occur

Probably a long time

#### Client version, Server revision & Game ID

Server Revision: [ea904cd81f16d6feb161b0dbd24eca7524df15ab](https://github.com/Foundation-19/Foundation-19/commit/ea904cd81f16d6feb161b0dbd24eca7524df15ab) - dev - 2022-07-28
Game ID: ci9-dgHD

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by checkraisefold** [comment]
>adds forensics robot
>doesnt check if autopsy scanner works
thank you baycoders...
