### ISSUE TITLE
BUG: Chairs on the left LCZ entry checkpoint tile lock you down.

### ISSUE THREAD

**Issue by Calyxman** [Foundation-19/Foundation-19#586]
#### Description of issue

Sometimes when you sit on the left lcz entry checkpoint, you cannot move after you unbuckle.
An admin asked me to make this bug report.

#### Difference between expected and actual behavior

I would be able to walk.
I was not able to.

#### Steps to reproduce

Sit on the chair on the left LCZ entry checkpoint tile

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

Server Revision: [ea904cd81f16d6feb161b0dbd24eca7524df15ab](https://github.com/Foundation-19/Foundation-19/commit/ea904cd81f16d6feb161b0dbd24eca7524df15ab) - dev - 2022-07-28
Game ID: cja-azua
Client Version: 514

#### Issue bingo

- [N] Issue could be reproduced at least once
- [N] Issue could be reproduced by different players
- [N/A] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ghost** [comment]
Tried most of the chairs near both LCZ checkpoints -- couldn't reproduce.

Do you have a picture of the specific chair?
