### ISSUE TITLE
Plastic surgery (or surgery in general?) Is broken

### ISSUE THREAD

**Issue by ThatOneCrusaderpilled** [Foundation-19/Foundation-19#592]
#### Description of issue
TRY doing plastic surgery, But you cant actually complete it.

#### Difference between expected and actual behavior
Surgery is supossed to be completable,  And Changes the Name and Voice of the person to something you set 

It isnt  even  possible to do it.

#### Steps to reproduce
1) use scapel to try to do plastic surgery (to peel away the skin)
2) you cant do anything plastic surgery  related after that

#### Specific information for locating
Scapel, Hemostat, surgery tools in general?

#### Length of time in which bug has been known to occur
Ever since The rebase, I assume

#### Client version, Server revision & Game ID
coudlnt get it, its something  in the game, take my baseless  evidenceless claims as truth!

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ThatOneCrusaderpilled** [comment]
Maybe its because I tried doing it as a surgery module Borg?

**Comment by ThatOneCrusaderpilled** [comment]
Oops.

**Comment by hry-gh** [comment]
it's not a surgical module thing, it's a borked surgical step at the moment. also, the code to change someone's name/face wasn't ported over at all, and doesn't exist rn

**Comment by ThatOneCrusaderpilled** [comment]
Noice.
