### ISSUE TITLE
SCP-049-2 zombies only use disarm attacks even when harm intent is selected.

### ISSUE THREAD

**Issue by qfmysteryman23** [Foundation-19/Foundation-19#602]
#### Description of issue
SCP-049-2 zombies can't use harm intent, even if the harm intent is selected. 

#### Difference between expected and actual behavior
SCP-049-2 zombies should be able to use the harm intent on people, but thats not the case. They are only able to use the disarm intent.

#### Steps to reproduce
SCP-049 creates a zombie, the zombie then attacks a person via the harm intent.

#### Length of time in which bug has been known to occur
	First reported 7/31/2022

#### Client version, Server revision & Game ID

Game ID: cjc-abCq
Client Version: 514
[8d98790edcb3c017fd4306d96565c40dee7d286d](https://github.com/Foundation-19/Foundation-19/commit/8d98790edcb3c017fd4306d96565c40dee7d286d) - dev - 2022-07-31

#### Issue bingo

- [ x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by projectkepler-ru** [comment]
please confirm, does this still happen?

**Comment by qfmysteryman23** [comment]
It does not still happen. The bug seems to be fixed
