### ISSUE TITLE
Agent ID Sprite Inspect Issue

### ISSUE THREAD

**Issue by MixMashy** [Foundation-19/Foundation-19#625]
#### Description of issue
Agent ID Card is showing up as normal sprite in the inspection when inspected upon even when a chameleon 

#### Difference between expected and actual behaviour
Agent ID Cards show up as whatever type of card you have chosen as the correct sprite

#### Steps to reproduce
Inspect Self after choosing your type of chameleon, Look at the sprite.

#### Specific information for locating

Agent ID Card.

#### Length of time in which bug has been known to occur

Guaranteed.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [daa442b2c928752b86b7eeafe8605d5d0b17c0f9](https://github.com/Foundation-19/Foundation-19/commit/daa442b2c928752b86b7eeafe8605d5d0b17c0f9) - dev - 2022-08-02
Game ID: cje-bCBe

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by hry-gh** [comment]
this is totally a player issue too, people can have replacement IDs that will always look like the base ID sprite. still a valid bug though, will look into it

**Comment by MixMashy** [comment]
It's just cause I kinda got shot for it. That's why I reported it and found it's just applied to any ID. Which is wierd

**Comment by theXDkidoflol** [comment]
this isn't just the agent ID, this goes for every chameleon item

**Comment by hry-gh** [comment]
> @MixMashy: It's just cause I kinda got shot for it. That's why I reported it and found it's just applied to any ID. Which is wierd

totally is still a bug, just meant people shouldn’t be killing people over a blank id anyway

**Comment by checkraisefold** [comment]
This was fixed by https://github.com/Foundation-19/Foundation-19/pull/896 close this
