### ISSUE TITLE
Chief Engineers ID Access Incorrect

### ISSUE THREAD

**Issue by MixMashy** [Foundation-19/Foundation-19#626]
#### Description of issue
Chief Engineers ID has missing access permissions.

#### Difference between expected and actual behaviour
Chief Engineer cannot access their own locker or go into places that engineers should have access to...

#### Steps to reproduce
Use Chief Engineers ID on his own locker and some doors

#### Specific information for locating

Chief Engineers ID

#### Length of time in which bug has been known to occur

Consistent on round start

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [daa442b2c928752b86b7eeafe8605d5d0b17c0f9](https://github.com/Foundation-19/Foundation-19/commit/daa442b2c928752b86b7eeafe8605d5d0b17c0f9) - dev - 2022-08-02
Game ID: cje-bCBe

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by hry-gh** [comment]
should be fixed by #585, i’ll check

**Comment by hry-gh** [comment]
<img width="408" alt="CleanShot 2022-08-03 at 14 06 44@2x" src="https://user-images.githubusercontent.com/55142896/182615278-2793b7a0-e613-4a17-9ef1-c32cb95e1173.png"> yep, will be fixed when #585 is merged

**Comment by MixMashy** [comment]
Ahh okay. You can do what you do with this then. Ha!
