### ISSUE TITLE
Leaping into airlocks can break them.

### ISSUE THREAD

**Issue by MicrowaveLord** [Foundation-19/Foundation-19#634]
#### Description of issue

Basicly, by leaping (Grab intent + Ctrl click in a far tile) into an airlock, you deal damage to it, as if you were thrown to it.

#### Difference between expected and actual behavior

I don't think that leaping and hitting a high tech airlock with your skull could damage it much if any damage could be done.

#### Steps to reproduce

I did this with athletics Trained level, allowing you to leap 3 tiles far.
Since i had not much to do, i decided to leap into CDZ's security's airlock and such.
Eventualy, someone else joined me on the Leaping-Into-The-Airlock bit, and, with enough effort and pain, the airlock suffered minor damage.
It's way eazier with multiple people to leap into it, but with one person is enough (Althought after dealing minor damage to the airlock, your skull will be probably broken and other bones too, etc.)

#### Specific information for locating

Drake Simmons crouches, preparing for a leap!

Drake Simmons takes a flying leap!

D-Block Entry was hit by Drake Simmons.

#### Length of time in which bug has been known to occur

Unsure, as this could have happend for a long time and maybe noone stood enough time bashing their own skulls into an airlock to find out.

#### Client version, Server revision & Game ID

Client Version: 514

Server Revision: [0e92bcb0079b09d7c897dd1f88ede8036439fcc2](https://github.com/Foundation-19/Foundation-19/commit/0e92bcb0079b09d7c897dd1f88ede8036439fcc2) - dev - 2022-08-04

Game ID: cjf-c16c

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ThatOneCrusaderpilled** [comment]
Its not a bug, its an unintended game feature, 100%

**Comment by hry-gh** [comment]
i'm okay with this bug
