### ISSUE TITLE
999# nullspace

### ISSUE THREAD

**Issue by Texicos** [Foundation-19/Foundation-19#636]
#### Description of issue 
999 is sent to nullspace when a host is killed while he is attached. Coming back from nullspace and clicking on any host again will send you back to nullspace.

#### Difference between expected and actual behavior
Instead of attaching or detaching, you are sent to nullspace.

#### Steps to reproduce
attach to a person, have that person get their head blown off. Come back and attach to anyone again.

#### Client version, Server revision & Game ID
cjg-aRHC

Server Revision: [0e92bcb0079b09d7c897dd1f88ede8036439fcc2](https://github.com/Foundation-19/Foundation-19/commit/0e92bcb0079b09d7c897dd1f88ede8036439fcc2) - dev - 2022-08-04

514

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by ghost** [comment]
999 sent to the shadow realm for letting someone die

**Comment by GenericTrash** [comment]
By the looks of things this is more of an issue for when someone gets gibbed and the SCP tries to follow their body which no longer exists. Havent been able to reproduce with just someone dying

**Comment by ghost** [comment]
Most likely 999 attempted to follow the parent of the mind of the player? Resulting in it following a brainmob that was sent to nullspace/qdel'd that was created after their head was gibbed.

**Comment by Magisterium2022** [comment]
Yes, absolutely. It’s the same issue as deleting a person, or following an item that gets deleted. I’ll try and set up a quick fix.
