### ISSUE TITLE
BUG: No hardsuit interface tab when wearing hardsuit

### ISSUE THREAD

**Issue by Calyxman** [Foundation-19/Foundation-19#655]
#### Description of issue

No hardsuit interface tab near Info section of UI.

#### Difference between expected and actual behavior

I would be able to use hardsuit verbs in a hardsuit interface tab, next to IC and Object.
I was not able to do so. I was not able to see a hardsuit interface tab.
#### Steps to reproduce
Equip and activate RIGsuit.
See problem.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

N/A, presumably since rebase

#### Client version, Server revision & Game ID

514, [02fc99c8bedd152fb3817ad05ce4941b072cec10](https://github.com/Foundation-19/Foundation-19/commit/02fc99c8bedd152fb3817ad05ce4941b072cec10) - dev - 2022-08-06, Game ID: cjj-ci5v

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by hry-gh** [comment]
![image](https://user-images.githubusercontent.com/55142896/184661706-4f877502-d856-4991-8d4c-67e106ef6b6f.jpeg)

got purged when we got TGUI'd

**Comment by DTraitor** [comment]
Right now I have enough knowledge to bring that panel back but I'm not going to do that unless someone makes a sane way to add your own tabs to statusbar

**Comment by checkraisefold** [comment]
it still works, ooc > tgui refresh makes it pop up
