### ISSUE TITLE
BUG: Paper examine doesn't work

### ISSUE THREAD

**Issue by Tsurupeta** [Foundation-19/Foundation-19#723]
Looking at it doesn't open its contents.

**Comment by hry-gh** [comment]
can't replicate on my local, were you ghosted at the time?

**Comment by Tsurupeta** [comment]
[20:12:10] Runtime in paper.dm, line 184: Cannot read "English".name
proc name: show content (/obj/item/paper/proc/show_content)
usr: Nettie Holmes (/mob/observer/ghost) ([0x3000054]) (the floor) (45,93,2) (/turf/simulated/floor/tiled/monotile) (voidshiki)
usr.loc: The floor (/turf/simulated/floor/tiled/monotile) ([0x1015cce]) (45,93,2) (/area/site53/llcz/scp131)
