### ISSUE TITLE
Spawn Location prevents late-joining.

### ISSUE THREAD

**Issue by TerryTehCoder** [Foundation-19/Foundation-19#74]
#### Description of issue
Setting your spawn location to "Light Containment Zone" prevents late-joining entirely. 

#### Difference between expected and actual behavior
Expected to be able to still latejoin aboard the arrivals tram, unable to latejoin at all.

#### Steps to reproduce
-Set character spawn location to Light Containment Zone. (Possibly others as well).
-Attempt to latejoin a round in progress.
-Latejoin menu refreshes everytime you select a job, nothing else happens.

#### Length of time in which bug has been known to occur
Not certain, generalized.

#### Client version, Server revision & Game ID

514, [d40bc9bfb8f238bdcd638a1ec0238490ff9e51c5], ciy-dp8e

#### Issue bingo

- [Untested] Issue could be reproduced at least once
- [Untested] Issue could be reproduced by different players
- [Untested] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by bigfloppa57** [comment]
disable LCZ spawning?

**Comment by ghost** [comment]
Seems to be working (on a local server).

You can even spawn inside LCZ as someone without access (e.g. D boys).

**Comment by TerryTehCoder** [comment]
> Seems to be working (on a local server).
> 
> 
> 

I'll test it out on a local branch and close it if that's the case. It _has_ been five months. 

> You can even spawn inside LCZ as someone without access (e.g. D boys).

This doesn't seem intentional.

**Comment by 77seven77seven** [comment]
Trams are gone, I think this should be closed. As far as I know this does not happen anymore.

**Comment by aidan-bowman** [comment]
Close issue?
