### ISSUE TITLE
Relocate all SCP's to one folder.

### ISSUE THREAD

**Issue by Tuulipommi** [Foundation-19/Foundation-19#812]
Self explanatory.

**Comment by checkraisefold** [comment]
please clarify this issue, they all seem to be in one folder in https://github.com/Foundation-19/Foundation-19/tree/dev/code/modules/SCP/SCPs already

**Comment by MACIEKBAKI** [comment]
> please clarify this issue, they all seem to be in one folder in https://github.com/Foundation-19/Foundation-19/tree/dev/code/modules/SCP/SCPs already

Most are, yes, but some (if I recall off the top of my head, scp-500?) are in random places (with 500 for instance being in *plate carriers* (why?))

**Comment by Tuulipommi** [comment]
> please clarify this issue, they all seem to be in one folder in https://github.com/Foundation-19/Foundation-19/tree/dev/code/modules/SCP/SCPs already

So... for example, SCP-500 is in the maps/site53/items/clothing/platecarriers.dm.

**Comment by checkraisefold** [comment]
> > please clarify this issue, they all seem to be in one folder in https://github.com/Foundation-19/Foundation-19/tree/dev/code/modules/SCP/SCPs already
> 
> So... for example, SCP-500 is in the maps/site53/items/clothing/platecarriers.dm.

is 500 the only scp that has this issue? if so change issue title, if not give complete list

**Comment by MACIEKBAKI** [comment]
> > > please clarify this issue, they all seem to be in one folder in https://github.com/Foundation-19/Foundation-19/tree/dev/code/modules/SCP/SCPs already
> > 
> > 
> > So... for example, SCP-500 is in the maps/site53/items/clothing/platecarriers.dm.
> 
> is 500 the only scp that has this issue? if so change issue title, if not give complete list

It's not, 013 had it too
Issue resolved by #831
