### ISSUE TITLE
everyone in radius blinks instantly after 173 cage opens

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#835]
#### Description of issue
title

#### Difference between expected and actual behavior
everyone should not blink instantly

#### Steps to reproduce
```
Jasper Coldsmith attempts to open SCP-173 Cage.
Jasper Coldsmith opens SCP-173 Cage!
Checkers Shafer blinks.
Jasper Coldsmith blinks.
Chad Blackburn blinks.
Unknown (as Zachary Hooker) blinks.
SCP-173 snaps Chad Blackburn's neck!
```

**Comment by 77seven77seven** [comment]
i vote agaisnt this, in my opinion 173 is already too weak and this balances it out in my opinion

**Comment by checkraisefold** [comment]
> i vote agaisnt this, in my opinion 173 is already too weak and this balances it out in my opinion

this is the most troll comment of all time
