### ISSUE TITLE
you can't pick up fireaxes from fireaxy things

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#837]
#### Description of issue
upon trying to pick up a fireaxe from a fireaxe cabinet you may find yourself with a problem, instead of being picken up, all you can do is OPEN or CLOSE the fireaxe cabinet.

#### Difference between expected and actual behavior
it opens and is picked up.

it opens and closes
#### Steps to reproduce
find fireaxe cabinet, unlock the maglock using either an ID or an Multitool.
try to open it then.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by Tsurupeta** [comment]
you drag fire cabinet sprite onto yourself to take axe out...

**Comment by reklaw9** [comment]
guh
