### ISSUE TITLE
BUG: APPARENTLY these 3 SCPs are broken.

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#888]
#### Description of issue
scp 513(the bell) is broken(can infect despite headphones)
that one spaghetti that screams eric seems to be broken(can scream despite headphones)
that one funny sign that kills you seems to be broken(apparently blindfolds don't work on it!)

I was told this by another player and have not tested it in game.

#### Steps to reproduce

Unknown.

#### Length of time in which bug has been known to occur

Unsure.

#### Client version, Server revision & Game ID

Unsure.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by checkraisefold** [comment]
for 066, headphones are NOT noise cancelling enough.. you can use earmuffs though
same with 513
151 while blindfolded is an actual bug and opening a pr to fix it

**Comment by reklaw9** [comment]
> for 066, headphones are NOT noise cancelling enough.. you can use earmuffs though same with 513 151 while blindfolded is an actual bug and opening a pr to fix it

with headphones i meant earmuffs
