### ISSUE TITLE
SCP-500 is in LCZ and not HCZ

### ISSUE THREAD

**Issue by ghost** [Foundation-19/Foundation-19#897]
#### Description of issue

SCP-500 isn't locked away properly. Anyone can rush it start-of-round, and then it's gone. Usually abused by command/sec/traitors. 

It should be moved to HCZ, where there's much greater oversight and consequences for stealing a godchem.

Neeps a map update. You can probably throw it into one of the various empty rooms that are taped-off (I assume these are just placeholders, and don't already have potential, not-yet-programmed SCPs to be contained there),

**Comment by checkraisefold** [comment]
considering 1102 is in hcz behind a gigantic fucking checkpoint while being a lot less valuable than 500, 500 should definitely be in hcz behind some fuckoff checkpoint

**Comment by checkraisefold** [comment]
closed by #900 if it gets merged

**Comment by 77seven77seven** [comment]
> closed by #900 if it gets merged

#929
