### ISSUE TITLE
Buckshot is broken 

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#902]
#### Description of issue
Seeems like buckshot is broken, visually it only shoots one bullet, tested with saiga12 shotgun

#### Difference between expected and actual behavior
buckshot shoots multiple bullets

one bulleto
#### Steps to reproduce
load shotgun with buckshot, shoot buckhost

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by Tsurupeta** [comment]
Not a bug, this is how bay handles buckshot.
