### ISSUE TITLE
ID card modification program doesn't let you set individual access

### ISSUE THREAD

**Issue by checkraisefold** [Foundation-19/Foundation-19#905]
#### Description of issue

title, you can only change assignment and not individual access levels
seems to have sprung up after #800 

#### Difference between expected and actual behavior

there's buttons to set each access level. they do nothing

#### Steps to reproduce

1. open id card mod program
2. put id in
3. try to edit individual accesses while you have ID computer access
4. discover you can only set assignment

**Comment by reklaw9** [comment]
this sounds like a access issue, which job?

**Comment by checkraisefold** [comment]
> this sounds like a access issue, which job?

even the sd can't set individual accesses. i can't as internal tribunal officer which is same as sd access, this is a bug

**Comment by reklaw9** [comment]
huh

**Comment by MACIEKBAKI** [comment]
hngnhngnhgn this is what happens when you push a change and dont test it
I'll look into this

**Comment by MACIEKBAKI** [comment]
can't replicate or it was fixed and the issue was not closed

**Comment by MACIEKBAKI** [comment]
can't reproduce
