### ISSUE TITLE
BUG: implanted HUDs don't work

### ISSUE THREAD

**Issue by reklaw9** [Foundation-19/Foundation-19#906]
#### Description of issue
NOTE:TESTED WITH MED HUD FROM CHAR SETUP

tried to use a HUD that i got from char setup and it didn't work, enabled and disabled it and it didn't do shit, tried to remove my current glasses etcetera, nothing happened
#### Difference between expected and actual behavior
health hud = health HUD overlay

health hud = 4 wasted points
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by Tsurupeta** [comment]
They require you to have medical/sec ID access to use.

**Comment by reklaw9** [comment]
they REALLY shouldn't need it, and also, why would you implant something in your eyes that needs you to have a ID on you at all times?

**Comment by Tsurupeta** [comment]
Ask the fucking bay12 devs that put it in place.

**Comment by MACIEKBAKI** [comment]
Yeah, it is really stupid

**Comment by ghost** [comment]
I'll work on this
