### ISSUE TITLE
Stairs not rotating correctly with view

### ISSUE THREAD

**Issue by aidan-bowman** [Foundation-19/Foundation-19#954]
#### Description of issue

When rotating view via "Spin View CW" or "Spin View CCW" verbs (which call the 'turn' function), the placement of stairs doesn't rotate correctly. See attached images:

![Default](https://user-images.githubusercontent.com/34486300/215852697-bc7a300d-d1d9-4ad7-8d30-50a9b33680f6.png)
![Incorrect](https://user-images.githubusercontent.com/34486300/215852706-1ad41683-1dd3-4d9c-a81b-09217192cc65.png)
![Incorrect](https://user-images.githubusercontent.com/34486300/215852718-e8286fc1-b38f-443c-8247-7c8860018093.png)
![Correct](https://user-images.githubusercontent.com/34486300/215852726-c15ff483-5129-4f73-b371-1b6833be7380.png)

#### Difference between expected and actual behavior

Stairs position should change to match when rotating, but don't.

#### Steps to reproduce

Use "Spin View CW" near any stairs object.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Not sure

#### Client version, Server revision & Game ID

Client: 514.1589
Server Revision: 2014338b4474767c2d60ed8c9a9bcffaf4223d06

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by aidan-bowman** [comment]
Didn't find this during any rounds; I saw this while testing unrelated changes that I made. Glitch still occurred on a clean branch.

**Comment by Tsurupeta** [comment]
Time to remove view spinning.

**Comment by MACIEKBAKI** [comment]
why is view spinning even a thing? *how does it even work?*

**Comment by MACIEKBAKI** [comment]
> why is view spinning even a thing? _how does it even work?_

```dm
/client/New()
	..()
	dir = NORTH

/client/verb/spinleft()
	set name = "Spin View CCW"
	set category = "OOC"
	dir = turn(dir, 90)

/client/verb/spinright()
	set name = "Spin View CW"
	set category = "OOC"
	dir = turn(dir, -90)
```
from byond docs on `/client/var/dir`:
`This defines the relationship between the world's coordinate system and the player's screen. The default means that the player sees the map exactly as it was created (in the map-editor or at runtime). Changing it to one of the other directions causes the player to see the map as if it were rotated to that direction. [...] 
Note that this does not turn icons upside down! The map is rotated, but the icons on the map remain in their normal orientation. `

**Comment by Tsurupeta** [comment]
It works in a very weird way, because bay doesn't support view rotation with it's doors and ladders and stuff like that.

**Comment by MACIEKBAKI** [comment]
> It works in a very weird way, because bay doesn't support view rotation with it's doors and ladders and stuff like that.

yeah it just uses dir var on client, which I was not aware even existed
