### ISSUE TITLE
Loadout items disappearing  into waist pack when waking up from cryo

### ISSUE THREAD

**Issue by chesse20** [Foundation-19/Foundation-19#967]
#### Description of issue
I spawned in and my backpack was full of items from my loadout so additional items were "placed into my waistpack" but the waistpack was empty when checked

#### Difference between expected and actual behavior
The items should have been in my waist pack as implied by the game logs
![image](https://user-images.githubusercontent.com/9161779/216795268-bba7dfa9-414d-45a9-b038-a99713b8dd31.png)

inside of the waistpack:
![image](https://user-images.githubusercontent.com/9161779/216795333-a2a07965-ff8a-4ddb-b26b-d01bf4c3534b.png)

#### Steps to reproduce
Have a bunch of large items and clothes in your loadout and a waistpack then join the round

#### Client version, Server revision & Game ID

Server Revision: [31aae158041869b81cc3c8be2760b7f848090f14](https://github.com/Foundation-19/Foundation-19/commit/31aae158041869b81cc3c8be2760b7f848090f14) - testing-branch - 2023-02-04
Game ID: cmd-dJ00
Current map: Foundation Site 53

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by reklaw9** [comment]
they spawned on a bag on your feet due to shitcode, essentially, it overwrites the normal code (of spawning a normal bag) and just spawns two bag, the bag you had on your char setup and a random bag on your feet

**Comment by reklaw9** [comment]
okay so uhhh actually its the other way around, the bag of your char setup spawns ON your feet, with your normal items, and a secondary bag appears in your back

**Comment by reklaw9** [comment]
add issue could be reproduced in multiple rounds+different players+atleast once

**Comment by chesse20** [comment]
> add issue could be reproduced in multiple rounds+different players+atleast once

Alright i checked those boxes
