### ISSUE TITLE
LCZ Security Breakroom has a wall in the door

### ISSUE THREAD

**Issue by Addust** [Foundation-19/Foundation-19#970]
#### Description of issue
<img width="103" alt="image" src="https://user-images.githubusercontent.com/80979251/217647794-65f801a6-8410-4ea1-8ad4-db50a8d99daf.png">
yea

#### Difference between expected and actual behavior

The door should NOT lead to a wall.

#### Steps to reproduce

Head over to LCZ security, open door

#### Specific information for locating

LCZ security

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

**Comment by Tsurupeta** [comment]
It's a local sight, exists there for more than 3 months
