### ISSUE TITLE
SCP-457's containment chamber lacks cameras

### ISSUE THREAD

**Issue by Addust** [Foundation-19/Foundation-19#974]
#### Description of issue
457's chamber area lacks cameras.

#### Difference between expected and actual behavior
It should have cameras.

#### Steps to reproduce
Be 457. No camera.

#### Specific information for locating

457 has no cameras.

#### Length of time in which bug has been known to occur

Since 457 was added

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

also it would be nice if he got an intercom

**Comment by 77seven77seven** [comment]
457 is still in the game? I'm pretty sure that PR was reverted....?

**Comment by aidan-bowman** [comment]
Close this issue, there is no 457.
